version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: studentcoin_db
    environment:
      POSTGRES_DB: studentcoin_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Serviço do Backend Spring Boot
  backend:
    container_name: studentcoin_backend
    # Este caminho já estava correto
    build: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: studentcoin_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    restart: on-failure

  # Serviço do Frontend React (servido com Nginx)
  frontend:
    container_name: studentcoin_frontend
    # CORREÇÃO: O caminho agora aponta para dentro da pasta 'Código'
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

# Define um volume nomeado para persistir os dados do banco de dados
volumes:
  postgres_data: